export const AUTOCOMPLETE_FALLBACK_MODELS_BY_PROVIDER = {
  "302ai": ["gemini-3-flash-preview"],
  abacus: ["gemini-3-flash-preview"],
  aihubmix: ["deepseek-v3.2-fast"],
  alibaba: ["qwen3-omni-flash"],
  "alibaba-cn": ["qwen3-omni-flash"],
  "amazon-bedrock": ["zai.glm-4.7-flash", "global.anthropic.claude-haiku-4-5-20251001-v1:0", "amazon.nova-2-lite-v1:0"],
  anthropic: ["claude-haiku-4-5", "claude-haiku-4-5-20251001", "claude-3-5-haiku-20241022"],
  azure: ["gpt-5.1-codex-mini", "gpt-5-mini", "gpt-5-nano", "claude-haiku-4-5"],
  "azure-cognitive-services": ["gpt-5.1-codex-mini", "gpt-5-mini", "gpt-5-nano", "claude-haiku-4-5"],
  bailing: ["Ling-1T"],
  baseten: ["moonshotai/Kimi-K2-Instruct-0905"],
  berget: ["mistralai/Mistral-Small-3.2-24B-Instruct-2506"],
  cerebras: ["qwen-3-235b-a22b-instruct-2507"],
  chutes: ["zai-org/GLM-4.7-Flash"],
  "cloudferro-sherlock": ["speakleash/Bielik-11B-v2.6-Instruct"],
  "cloudflare-ai-gateway": ["workers-ai/@cf/ibm-granite/granite-4.0-h-micro"],
  "cloudflare-workers-ai": ["@cf/ibm-granite/granite-4.0-h-micro"],
  cohere: ["command-a-translate-08-2025", "command-a-reasoning-08-2025", "command-a-03-2025"],
  cortecs: ["devstral-small-2512"],
  deepinfra: ["zai-org/GLM-4.7-Flash"],
  deepseek: ["deepseek-chat", "deepseek-reasoner"],
  evroc: ["mistralai/devstral-small-2-24b-instruct-2512"],
  fastrouter: ["openai/gpt-5-nano"],
  "fireworks-ai": [
    "accounts/fireworks/models/kimi-k2-instruct",
    "accounts/fireworks/models/glm-5",
    "accounts/fireworks/models/minimax-m2p5",
  ],
  firmware: ["gemini-3-flash-preview"],
  friendli: ["Qwen/Qwen3-235B-A22B-Instruct-2507"],
  "github-copilot": ["gpt-5-mini", "gemini-3-flash-preview", "claude-haiku-4.5", "gpt-5.1-codex-mini"],
  "github-models": ["openai/gpt-4.1-nano", "openai/gpt-4.1-mini", "mistral-ai/mistral-small-2503"],
  gitlab: ["duo-chat-gpt-5-mini"],
  google: ["gemini-3.1-flash-lite-preview", "gemini-3-flash-preview", "gemini-2.5-flash-lite-preview-09-2025"],
  "google-vertex": ["gemini-3-flash-preview", "gemini-flash-lite-latest", "gemini-2.5-flash-lite-preview-09-2025"],
  "google-vertex-anthropic": ["claude-haiku-4-5@20251001", "claude-3-5-haiku@20241022", "claude-sonnet-4-6@default"],
  groq: ["llama-3.1-8b-instant", "openai/gpt-oss-20b", "moonshotai/kimi-k2-instruct-0905"],
  helicone: ["grok-4-1-fast-non-reasoning"],
  huggingface: ["XiaomiMiMo/MiMo-V2-Flash"],
  iflowcn: ["qwen3-235b-a22b-instruct"],
  inception: ["mercury"],
  inference: ["meta/llama-3.1-8b-instruct"],
  "io-net": ["mistralai/Magistral-Small-2506"],
  jiekou: ["gpt-5-nano"],
  kilo: ["stepfun/step-3.5-flash"],
  "kimi-for-coding": ["k2p5"],
  "kuae-cloud-coding-plan": ["GLM-4.7"],
  llama: ["cerebras-llama-4-maverick-17b-128e-instruct"],
  lmstudio: ["qwen/qwen3-30b-a3b-2507"],
  lucidquery: ["lucidquery-nexus-coder"],
  meganova: ["XiaomiMiMo/MiMo-V2-Flash"],
  minimax: ["MiniMax-M2.5-highspeed", "MiniMax-M2.5", "MiniMax-M2.1"],
  "minimax-cn": ["MiniMax-M2.5-highspeed", "MiniMax-M2.5", "MiniMax-M2.1"],
  "minimax-cn-coding-plan": ["MiniMax-M2.5-highspeed", "MiniMax-M2.5", "MiniMax-M2.1"],
  "minimax-coding-plan": ["MiniMax-M2.5-highspeed", "MiniMax-M2.5", "MiniMax-M2.1"],
  mistral: ["labs-devstral-small-2512", "devstral-small-2507", "mistral-small-2506"],
  moark: ["GLM-4.7"],
  modelscope: ["Qwen/Qwen3-Coder-30B-A3B-Instruct"],
  moonshotai: ["kimi-k2.5", "kimi-k2-thinking-turbo", "kimi-k2-turbo-preview"],
  "moonshotai-cn": ["kimi-k2-thinking-turbo"],
  morph: ["morph-v3-fast"],
  "nano-gpt": ["mistralai/devstral-2-123b-instruct-2512"],
  nebius: ["Qwen/Qwen3-32B-fast"],
  nova: ["nova-2-lite-v1"],
  "novita-ai": ["zai-org/glm-4.7-flash"],
  nvidia: ["nvidia/nvidia-nemotron-nano-9b-v2"],
  "ollama-cloud": ["gemini-3-flash-preview"],
  openai: ["gpt-5.3-codex-spark", "gpt-5.1-codex-mini", "gpt-5-mini", "gpt-5-nano"],
  opencode: ["gemini-3-flash"],
  "opencode-go": ["glm-5"],
  openrouter: [
    "stepfun/step-3.5-flash",
    "openai/gpt-5-nano",
    "google/gemini-2.5-flash-lite",
    "anthropic/claude-haiku-4.5",
  ],
  ovhcloud: ["mistral-small-3.2-24b-instruct-2506"],
  perplexity: ["sonar", "sonar-pro", "sonar-deep-research"],
  "perplexity-agent": ["google/gemini-3-flash-preview"],
  poe: ["novita/glm-4.7-flash"],
  "privatemode-ai": ["qwen3-coder-30b-a3b"],
  "qihang-ai": ["gemini-2.5-flash"],
  "qiniu-ai": ["x-ai/grok-4.1-fast-non-reasoning"],
  requesty: ["google/gemini-3-flash-preview"],
  "sap-ai-core": ["anthropic--claude-4.5-haiku"],
  scaleway: ["voxtral-small-24b-2507"],
  siliconflow: ["stepfun-ai/Step-3.5-Flash", "MiniMaxAI/MiniMax-M2.1", "zai-org/GLM-5"],
  "siliconflow-cn": ["stepfun-ai/Step-3.5-Flash", "Pro/MiniMaxAI/MiniMax-M2.1", "Pro/zai-org/GLM-5"],
  stackit: ["cortecs/Llama-3.3-70B-Instruct-FP8-Dynamic"],
  stepfun: ["step-3.5-flash"],
  submodel: ["Qwen/Qwen3-235B-A22B-Instruct-2507"],
  synthetic: ["hf:moonshotai/Kimi-K2-Instruct-0905"],
  togetherai: ["Qwen/Qwen3-Coder-Next-FP8", "zai-org/GLM-5", "MiniMaxAI/MiniMax-M2.5"],
  upstage: ["solar-mini"],
  v0: ["v0-1.5-lg"],
  venice: ["olafangensan-glm-4.7-flash-heretic"],
  vercel: ["alibaba/qwen3.5-flash", "openai/gpt-5.1-codex-mini", "openai/gpt-5-nano", "anthropic/claude-haiku-4.5"],
  vivgrid: ["gemini-3-flash-preview"],
  vultr: ["qwen2.5-coder-32b-instruct"],
  wandb: ["microsoft/Phi-4-mini-instruct"],
  xai: ["grok-4.20-experimental-beta-0304-non-reasoning", "grok-4-1-fast-non-reasoning", "grok-4-fast-non-reasoning"],
  xiaomi: ["mimo-v2-flash"],
  zai: ["glm-5", "glm-4.7-flash", "glm-4.5-flash"],
  "zai-coding-plan": ["glm-4.7-flash"],
  zenmux: ["volcengine/doubao-seed-2.0-mini"],
  zhipuai: ["glm-5", "glm-4.7-flash", "glm-4.5-flash"],
  "zhipuai-coding-plan": ["glm-4.6v-flash"],
} as const

export const AUTOCOMPLETE_FAST_MODEL_BY_PROVIDER = AUTOCOMPLETE_FALLBACK_MODELS_BY_PROVIDER
